// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsobnyjplkbyhrkldkns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzb2JueWpwbGtieWhya2xka25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2Mjg2OTksImV4cCI6MjA3OTIwNDY5OX0.GT9naF-PfFEl8Hb9YJvBCvr0J6Rl5nPdtNhEbjOtqLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});